scaledObjects:
  - name:  q01-corporate-actions-loader-file-event-stream
    namespace: swp-corporate-actions
    pollingInterval: 23 
    cooldownPeriod: 300 
    minReplicaCount: 10 
    maxReplicaCount: 11 
    scaleTargetRef:
      kind: Statefulsets
      name: q01-corporate-actions-loader-file-event-stream
    triggers:
      - type: 4
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01-5
          topic: q01_6
          lagThreshold: 300 
      - type: 4
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01-8
          topic: q01_9
          lagThreshold: 300 
      - type: 10
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01-11
          topic: q01_12
          lagThreshold: 300 
      - type: 13
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01-14
          topic: q01_15
          lagThreshold: 300 
      - type: 16
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01-17
          topic: q01_18
          lagThreshold: 300 
      - type: 19
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01-20
          topic: q01_21
          lagThreshold: 300 
      - type: 22
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01-23
          topic: q01_24
          lagThreshold: 300 
      - type: 25
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01-26
          topic: q01_27
          lagThreshold: 300 
      - type: 28
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01-29
          topic: q01_30
          lagThreshold: 300 
      - type: 31
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01-32
          topic: q01_33
          lagThreshold: 300 
