scaledObjects:
  - name:  q01-asasda
    namespace: swp-corporate-temp
    pollingInterval: 77 
    cooldownPeriod: 500 
    minReplicaCount: 78 
    maxReplicaCount: 79 
    scaleTargetRef:
      #kind: Deployment
      name: q01-asasda
    triggers:
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q011
          topic: q012
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: 3
          topic: 4
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: 5
          topic: 6
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: 7
          topic: 8
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01-9
          topic: q01_10
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q0111
          topic: q0112
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q0113
          topic: q0114
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q0115
          topic: q0116
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: 17
          topic: 18
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q0119
          topic: q0120
          lagThreshold: 500 
  - name:  q01-temp
    namespace: temp
    pollingInterval: 77 
    cooldownPeriod: 500 
    minReplicaCount: 78 
    maxReplicaCount: 79 
    scaleTargetRef:
      #kind: Deployment
      name: q01-temp
    triggers:
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: loader-file-event-stream-consumer-temp
          topic: EDB_DRF_LOAD_RECORD_temp
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01loader-file-event-stream-consumer-temp
          topic: q01EDB_DRF_LOAD_RECORD_temp
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01loader-file-event-stream-consumer-temp
          topic: q01EDB_DRF_LOAD_RECORD_temp
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01loader-file-event-stream-consumer-temp
          topic: q01EDB_DRF_LOAD_RECORD_temp
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: loader-file-event-stream-consumer-temp
          topic: EDB_DRF_LOAD_RECORD_temp
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: loader-file-event-stream-consumer-temp
          topic: EDB_DRF_LOAD_RECORD_temp
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: loader-file-event-stream-consumer-temp
          topic: EDB_DRF_LOAD_RECORD_temp
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: loader-file-event-stream-consumer-temp
          topic: EDB_DRF_LOAD_RECORD_temp
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: q01loader-file-event-stream-consumer-temp
          topic: q01EDB_DRF_LOAD_RECORD_temp
          lagThreshold: 500 
      - type: kafka
        metadata:
          bootstrapServers: QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092,QA.QA.SEIC.COM:9092 
          consumerGroup: loader-file-event-stream-consumer-temp
          topic: EDB_DRF_LOAD_RECORD_temp
          lagThreshold: 500 
