{{- range .Values.scaledObjects }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  scaleTargetRef:
    name: {{ .name }}-deployment
  pollingInterval: {{ .pollingInterval }}
  cooldownPeriod: {{ .cooldownPeriod }}
  minReplicaCount: {{ .minReplicaCount }}
  maxReplicaCount: {{ .maxReplicaCount }}
  triggers:
  {{- range .triggers }}
  - type: {{ .type }}
    metadata:
      bootstrapServers: {{ .metadata.bootstrapServers }}
      consumerGroup: {{ .metadata.consumerGroup }}
      topic: {{ .metadata.topic }}
      lagThreshold: {{ .metadata.lagThreshold }}
  {{- end }}
{{- end }}
